export const CHANGE_CURRENT_SONG = "player/CHANGE_CURRENT_SONG";

export const CHANGE_PLAY_LIST = "player/CHANGE_PLAY_LIST";

export const CHANGE_CURRENT_SONG_INDEX = "player/CHANGE_CURRENT_SONG_INDEX";

export const CHANGE_ORDER = "play/CHANGE_ORDER";

export const CHANGE_LYRICS_LIST = "player/CHANGE_LYRICS_LIST";

export const CHANGE_CURRENT_LYRIC_INDEX = "player/CHANGE_CURRENT_LYRIC_INDEX";

export const CHANG_RELEVANT_INFORMATION = "player/CHANG_RELEVANT_INFORMATION";