export const CHANGE_RECOMMEND_PROGRAM = "djradio/CHANGE_RECOMMEND_PROGRAM";

export const CHANGE_PROGRAM_TOPLIST = "djradio/CHANGE_PROGRAM_TOPLIST";

export const CHANGE_RECOMMEND_TYPE = "djradio/CHANGE_RECOMMEND_TYPE";